# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AnimeTagger.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'AnimeTagger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x41nimeTagger.proto\"\"\n\x0cImageMessage\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"V\n\rImageResponse\x12\x16\n\x0e\x63haracter_tags\x18\x01 \x03(\t\x12\x14\n\x0cgeneral_tags\x18\x02 \x03(\t\x12\x17\n\x06rating\x18\x03 \x01(\x0e\x32\x07.Rating*D\n\x06Rating\x12\x0b\n\x07General\x10\x00\x12\r\n\tSensitive\x10\x01\x12\x10\n\x0cQuestionable\x10\x02\x12\x0c\n\x08\x45xplicit\x10\x03\x32\x39\n\x0b\x41nimeTagger\x12*\n\x07GetTags\x12\r.ImageMessage\x1a\x0e.ImageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AnimeTagger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RATING']._serialized_start=145
  _globals['_RATING']._serialized_end=213
  _globals['_IMAGEMESSAGE']._serialized_start=21
  _globals['_IMAGEMESSAGE']._serialized_end=55
  _globals['_IMAGERESPONSE']._serialized_start=57
  _globals['_IMAGERESPONSE']._serialized_end=143
  _globals['_ANIMETAGGER']._serialized_start=215
  _globals['_ANIMETAGGER']._serialized_end=272
# @@protoc_insertion_point(module_scope)
