# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pixiv.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pixiv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpixiv.proto\x12\x08pixiv.v1\",\n\x13ValidateAuthRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"\'\n\x14ValidateAuthResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"]\n\x13GetBookmarksRequest\x12\x15\n\rpixiv_user_id\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x18\n\x10\x64ownload_private\x18\x03 \x01(\x08\"=\n\x14GetBookmarksResponse\x12%\n\tbookmarks\x18\x01 \x03(\x0b\x32\x12.pixiv.v1.Bookmark\"\x16\n\x08\x42ookmark\x12\n\n\x02id\x18\x01 \x01(\t\"\x86\x01\n\x0fGetImageRequest\x12\x12\n\nartwork_id\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\'\n\x07quality\x18\x03 \x01(\x0e\x32\x16.pixiv.v1.ImageQuality\x12\x11\n\tall_pages\x18\x04 \x01(\x08\x12\x0c\n\x04page\x18\x05 \x01(\x05\"<\n\x10GetImageResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t*7\n\x0cImageQuality\x12\r\n\tTHUMBNAIL\x10\x00\x12\n\n\x06MEDIUM\x10\x01\x12\x0c\n\x08ORIGINAL\x10\x02\x32\xbb\x02\n\x0cPixivManager\x12M\n\x0cGetBookmarks\x12\x1d.pixiv.v1.GetBookmarksRequest\x1a\x1e.pixiv.v1.GetBookmarksResponse\x12\x41\n\x08GetImage\x12\x19.pixiv.v1.GetImageRequest\x1a\x1a.pixiv.v1.GetImageResponse\x12M\n\x0cValidateAuth\x12\x1d.pixiv.v1.ValidateAuthRequest\x1a\x1e.pixiv.v1.ValidateAuthResponse\x12J\n\x0bHealthCheck\x12\x1c.pixiv.v1.HealthCheckRequest\x1a\x1d.pixiv.v1.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pixiv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEQUALITY']._serialized_start=554
  _globals['_IMAGEQUALITY']._serialized_end=609
  _globals['_VALIDATEAUTHREQUEST']._serialized_start=25
  _globals['_VALIDATEAUTHREQUEST']._serialized_end=69
  _globals['_VALIDATEAUTHRESPONSE']._serialized_start=71
  _globals['_VALIDATEAUTHRESPONSE']._serialized_end=110
  _globals['_GETBOOKMARKSREQUEST']._serialized_start=112
  _globals['_GETBOOKMARKSREQUEST']._serialized_end=205
  _globals['_GETBOOKMARKSRESPONSE']._serialized_start=207
  _globals['_GETBOOKMARKSRESPONSE']._serialized_end=268
  _globals['_BOOKMARK']._serialized_start=270
  _globals['_BOOKMARK']._serialized_end=292
  _globals['_GETIMAGEREQUEST']._serialized_start=295
  _globals['_GETIMAGEREQUEST']._serialized_end=429
  _globals['_GETIMAGERESPONSE']._serialized_start=431
  _globals['_GETIMAGERESPONSE']._serialized_end=491
  _globals['_HEALTHCHECKREQUEST']._serialized_start=493
  _globals['_HEALTHCHECKREQUEST']._serialized_end=513
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=515
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=552
  _globals['_PIXIVMANAGER']._serialized_start=612
  _globals['_PIXIVMANAGER']._serialized_end=927
# @@protoc_insertion_point(module_scope)
