services:
  AnimeTagger:
    ports:
      - "50051:50051"
    profiles: ["Tagger"]

  imagemanager:
    user: "${UID}:${GID}"
    ports:
      - "8080:8080"
    volumes:
      - "./ImageManager/images/:/Images"
      - "./ImageManager/import/:/Import"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    profiles: ["Backend"]

  frontend:
    ports: 
      - "3000:3000"
    profiles: ["Frontend"]

  database:
    ports:
      - "5432:5432"
